### ISSUE TITLE
Misuse of std::vector<T>::reserve

### ISSUE THREAD

**Issue by Hemofektik** [gerazo/loose_quadtree#2]
Running the LooseQuadtreeTest.cpp in MSVC causes an exception because on stl vector is called reserve() instead of resize():

```
std::vector<BoundingBox<NumberT>> objects;
objects.reserve(objects_generated);
```

The following code is accessing the objects via the operator[] but this may cause undefined behavior based on the STL implementation, since the size() of a vector does not change by calling reserve on it.

When fixing it, the compiler complains about BoundingBox<NumberT> not having a default constructor. Either the testing code needs to be changed to work somehow else or a default constructor needs to be added to the BoundingBox<NumberT> class.

Regards,
Richard

**Comment by gerazo** [comment]
Thank you for spotting the bug. Please check https://github.com/gerazo/loose_quadtree/commit/d6a453524234fd286237360fde661a0a7d1ff8c6 Did it fix the problem?

**Comment by Hemofektik** [comment]
Quick and clean fix. Neat...

Thanks for sharing this awesome library at all, it's a great piece of work.
